### ISSUE TITLE
Bad indentation in the metadata file

### ISSUE THREAD

**Issue by philpott** [123Loadboard/123Connect-gtm-template#2]
https://github.com/123Loadboard/123Connect-gtm-template/blob/e249425ebc4f547c17da9321a7ff2307666c6dd8/metadata.yaml#L6

Looks like this should be |2 vs |3 the yaml parser is throwing an exception when parsing this file.

**Comment by joaotargino** [comment]
- removed the |3 and |2 (looking on other sources it looks that it isn't necessary at all)
- fixed bad indentation issue
